services:
  resolver:
    image: docker.io/adguard/adguardhome:v0.107.78
    volumes:
      - ./adguardhome/work:/opt/adguardhome/work
      - ./adguardhome/conf:/opt/adguardhome/conf
      - ./acme.sh/<DOMAIN>_ecc/:/opt/adguardhome/certs
    ports:
      - "53:53/tcp" # Plain DNS
      - "53:53/udp" # Plain DNS
      - "853:853/tcp" # DNS-over-TLS
#      - "3000:3000/tcp" # Start-up page HTTP
    restart: unless-stopped

  sync:
    image: ghcr.io/bakito/adguardhome-sync:v0.9.2
    command: run --config /config/adguardhome-sync.yaml
    volumes:
      - ./sync:/config
    restart: unless-stopped

  acme.sh:
    image: ghcr.io/acmesh-official/acme.sh:3.1.4
    command: daemon
    restart: unless-stopped
    volumes:
      - "./acme.sh:/acme.sh"
    env_file:
      - .cf_token

networks:
  default:
    name: adguardhome
    external: True
